FROM node:20-bookworm-slim

WORKDIR /app

ENV HUSKY=0
ENV PORT=3000

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl \
  && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

RUN corepack enable && yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "dev:watch"]
