version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: sprint-sync-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_NAME=sprint-sync
      - DB_USER=sprintsync
      - DB_PASSWORD=sprintsync123
      - DB_MIN_POOL_SIZE=2
      - DB_MAX_POOL_SIZE=5
      - JWT_ISSUER=sprint-sync
      - JWT_AUDIENCE=sprint-sync-users
      - JWT_ACCESS_TOKEN_VALIDITY=3600
      - JWT_REFRESH_TOKEN_VALIDITY=86400
      - JWT_SECRET=dev-secret-key-change-in-production
      - OPENAI_KEY=${OPENAI_KEY:-}
      - CORS_URL=http://localhost:3001
      - LOG_DIR=logs
    depends_on:
      - mongodb
    networks:
      - sprint-sync-network
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: sprint-sync-db-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sprintsync
      - MONGO_INITDB_ROOT_PASSWORD=sprintsync123
      - MONGO_INITDB_DATABASE=sprint-sync
    volumes:
      - mongodb_data_dev:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - sprint-sync-network
    restart: unless-stopped

volumes:
  mongodb_data_dev:
    driver: local

networks:
  sprint-sync-network:
    driver: bridge
