name: Test and Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '20.x'
        type: string
      upload-coverage:
        description: 'Whether to upload test coverage'
        required: false
        default: false
        type: boolean

jobs:
  test-and-build:
    name: Test & Build (Node ${{ inputs.node-version }})
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run tests
      run: yarn test
      env:
        NODE_ENV: test
        
    - name: Build application
      run: yarn build
      
    - name: Upload test coverage
      if: ${{ inputs.upload-coverage }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ inputs.node-version }}
        path: coverage/
        retention-days: 7
